
development:
  adapter: postgresql
  encoding: unicode
  database: kick_it_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: kick_it_test
  pool: 5
  host: localhost